<a href="https://colab.research.google.com/github/sabrinadsll/Projeto-Lista-de-Tarefas/blob/main/C%C3%B3pia_de_T%C3%B3picos_An%C3%A1lise_de_Dados_Lista_pr%C3%A1tica_de_exerc%C3%ADcios_Primeiros_passos_para_uma_An%C3%A1lise_Explorat%C3%B3ria_de_Dados_com_Python_e_Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista 1 - **Primeiros passos para uma Análise Exploratória de Dados com Python e Pandas**


Este notebook tem como objetivo proporcionar uma introdução prática ao uso da biblioteca Pandas para coleta, limpeza e análise exploratória de dados. Ao completar os desafios propostos, os alunos exploram habilidades fundamentais como leitura de arquivos CSV, tratamento de dados faltantes, agrupamento, agregação e criação de visualizações básicas (boxplot e histograma) com Matplotlib ([documentação aqui](https://matplotlib.org/)). A documentação completa do *Pandas* está disponível [aqui](https://pandas.pydata.org/docs/), onde é possível explorar mais sobre as funções usadas neste notebook - *é fundamental que vocês vejam a documentação!*

Este notebook está dividido em duas etapas principais: Coleta e Limpeza de Dados, e Análise Exploratória.
Cada etapa apresenta desafios que devem ser resolvidos usando as funcionalidades do *Pandas*.

---

## **Etapa 1: Coleta e Limpeza de Dados**

### **Desafio 1: Carregar um arquivo CSV**


Faça o *import* da biblioteca Pandas;

Leia [este arquivo](https://docs.google.com/spreadsheets/d/1DNcQLaNmd7zz4Ek21DE4ilQyNlgBocTFpapQN5RX7mU/pub?gid=945868634&single=true&output=csv) (.csv) e exiba as primeiras 5 linhas da tabela. Em seguida, imprima a descrição das colunas e seus respectivos tipos.


**Para entender o contexto:**

A análise de dados do orçamento público, especialmente das emendas parlamentares, é um tema de extrema relevância no Brasil, pois evidencia a dinâmica democrática na alocação de recursos financeiros em nosso país. As emendas parlamentares representam uma forma dos legisladores deliberarem sobre a destinação de verbas, refletindo, em tese, as demandas e prioridades de diferentes regiões e setores da sociedade. Nesta atividade você terá a oportunidade de aplicar os conceitos explorados em estatística para analisar dados reais do orçamento público brasileiro de 2025.

Os dados foram obtidos em 21/09/2026, no [Painel do Orçamento Federal](https://www1.siop.planejamento.gov.br/qlikview/index.htm) e estão disponíveis [neste link](https://drive.google.com/file/d/1hzfeNHytFFAHBI1tHWcOWVxGkstaaM6l/view?usp=sharing), distribuídos nas seguintes colunas: Ano, RP, Autor, Tipo Autor, Partido, UF Autor, Nro. Emenda, Órgão, Ação, Dotação Inicial, Emenda, Dotação Atual Emenda, Empenhado, Liquidado, Pago. Para saber mais sobre os dados, acesse: [O que é o orçamento federal](https://www.gov.br/pt-br/servicos/consultar-dados-no-painel-do-orcamento-federal) e [Entenda a Gestão - Emendas Parlamentares](https://portaldatransparencia.gov.br/pagina-interna/605525-emendas-parlamentares#:~:text=Emenda%20parlamentar%20%C3%A9%20um%20instrumento,lei%20or%C3%A7ament%C3%A1ria%20enviado%20pelo%20Executivo.).

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
path = "https://www.google.com/url?q=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1DNcQLaNmd7zz4Ek21DE4ilQyNlgBocTFpapQN5RX7mU%2Fpub%3Fgid%3D945868634%26single%3Dtrue%26output%3Dcsv"

In [4]:
df = pd.read_csv(path)

In [5]:
df.head()

,Ano,RP,Autor,Tipo Autor,Partido,UF Autor,Nro. Emenda,Órgão,Ação,Dotação Inicial Emenda,Dotação Atual Emenda,Empenhado,Liquidado,Pago
0,2023,6 - Emendas Individuais,Abílio Santana,Deputado Federal,PSC,BA,38950001,36000 - Ministério da Saúde,2E89 - Incremento Temporário ao Custeio dos Se...,3.258.419,1.500.000,1.500.000,1.500.000,1.500.000
1,2023,6 - Emendas Individuais,Abílio Santana,Deputado Federal,PSC,BA,38950002,36000 - Ministério da Saúde,2E89 - Incremento Temporário ao Custeio dos Se...,2.443.813,2.000.000,2.000.000,2.000.000,2.000.000
2,2023,6 - Emendas Individuais,Abílio Santana,Deputado Federal,PSC,BA,38950003,36000 - Ministério da Saúde,2E89 - Incremento Temporário ao Custeio dos Se...,411.292,8.218.164,8.218.164,8.218.164,8.218.164
3,2023,6 - Emendas Individuais,Abílio Santana,Deputado Federal,PSC,BA,38950004,36000 - Ministério da Saúde,2E89 - Incremento Temporário ao Custeio dos Se...,814.604,0,0,0,0
4,2023,6 - Emendas Individuais,Abílio Santana,Deputado Federal,PSC,BA,38950004,36000 - Ministério da Saúde,2E90 - Incremento Temporário ao Custeio dos Se...,0,600.000,600.000,600.000,600.000

In [6]:
df.shape

(7090, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Ano                     7090 non-null   int64
 1   RP                      7090 non-null   object
 2   Autor                   7090 non-null   object
 3   Tipo Autor              7090 non-null   object
 4   Partido                 7090 non-null   object
 5   UF Autor                7090 non-null   object
 6   Nro. Emenda             7090 non-null   int64
 7   Órgão                   7090 non-null   object
 8   Ação                    7090 non-null   object
 9   Dotação Inicial Emenda  7090 non-null   object
 10  Dotação Atual Emenda    7090 non-null   object
 11  Empenhado               7090 non-null   object
 12  Liquidado               7090 non-null   object
 13  Pago                    7090 non-null   object
dtypes: int64(2), object(12)
memory usage: 775.6+ KB

### **Desafio 2: Ajustar nomes de colunas**

Após carregar os dados, ajuste os nomes das colunas para garantir que não haja espaços ou caracteres especiais. Por exemplo, a coluna "UF Autor" deve ser transformada em "uf_autor".

In [8]:
df.rename(columns={
    'Ano':'ano',
    'RP':'rp',
    'Autor':'autor',
    'Tipo Autor':'tipo_autor',
    'Partido':'partido',
    'UF Autor':'uf_autor',
    'Nro. Emenda':'num_emenda',
    'Órgão':'orgao',
    'Ação':'acao',
    'Dotação Inicial Emenda':'dotacao_inicial_emenda',
    'Dotação Atual Emenda':'dotacao_atual_emenda',
    'Empenhado':'empenhado',
    'Liquidado':'liquidado',
    'Pago':'pago'
}, inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ano                     7090 non-null   int64
 1   rp                      7090 non-null   object
 2   autor                   7090 non-null   object
 3   tipo_autor              7090 non-null   object
 4   partido                 7090 non-null   object
 5   uf_autor                7090 non-null   object
 6   num_emenda              7090 non-null   int64
 7   orgao                   7090 non-null   object
 8   acao                    7090 non-null   object
 9   dotacao_inicial_emenda  7090 non-null   object
 10  dotacao_atual_emenda    7090 non-null   object
 11  empenhado               7090 non-null   object
 12  liquidado               7090 non-null   object
 13  pago                    7090 non-null   object
dtypes: int64(2), object(12)
memory usage: 775.6+ KB

### **Desafio 3: Ajustar valores em algumas colunas**

Melhore a apresentação de dados em algumas colunas, por exemplo, separe o número do texto da coluna "Órgão". Descreva as operações que você fez ao finalizar esta etapa.

**Importante:** As colunas 'Dotação Inicial', 'Emenda','Dotação Atual Emenda',	'Empenhado',	'Liquidado' e	'Pago' precisam ser tratadas. Retire os "." e transforme em *float* estas colunas.

In [10]:
df['orgao'].head()

0    36000 - Ministério da Saúde
1    36000 - Ministério da Saúde
2    36000 - Ministério da Saúde
3    36000 - Ministério da Saúde
4    36000 - Ministério da Saúde
Name: orgao, dtype: object

In [16]:
df['codigo_orgao'] = df['orgao'].apply(
    lambda x: x.split(' - ')[0]
)

criei a coluna codigo_orgao, depois peguei cada valor da coluna orgao e
separei o texto usando o split onde tinha o -, depois usei o índice 0 para pegar a primeira parte

In [12]:
df['nome_orgao'] = df['orgao'].apply(
    lambda x: x.split(' - ')[1]
)

In [13]:
df[['orgao', 'codigo_orgao', 'nome_orgao']].head()

                         orgao codigo_orgao           nome_orgao
0  36000 - Ministério da Saúde        36000  Ministério da Saúde
1  36000 - Ministério da Saúde        36000  Ministério da Saúde
2  36000 - Ministério da Saúde        36000  Ministério da Saúde
3  36000 - Ministério da Saúde        36000  Ministério da Saúde
4  36000 - Ministério da Saúde        36000  Ministério da Saúde

In [23]:
df['dotacao_inicial_emenda'] = df['dotacao_inicial_emenda'].apply(
    lambda x: x.replace('.', '')
)

df['dotacao_atual_emenda'] = df['dotacao_atual_emenda'].apply(
    lambda x: x.replace('.', '')
)

df['empenhado'] = df['empenhado'].apply(
    lambda x: x.replace('.', '')
)

df['liquidado'] = df['liquidado'].apply(
    lambda x: x.replace('.', '')
)

df['pago'] = df['pago'].apply(
    lambda x: x.replace('.', '')
)

In [24]:
df = df.astype({
    'dotacao_inicial_emenda':'float',
    'dotacao_atual_emenda':'float',
    'empenhado':'float',
    'liquidado':'float',
    'pago':'float'
})

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ano                     7090 non-null   int64
 1   rp                      7090 non-null   object
 2   autor                   7090 non-null   object
 3   tipo_autor              7090 non-null   object
 4   partido                 7090 non-null   object
 5   uf_autor                7090 non-null   object
 6   num_emenda              7090 non-null   int64
 7   orgao                   7090 non-null   object
 8   acao                    7090 non-null   object
 9   dotacao_inicial_emenda  7090 non-null   float64
 10  dotacao_atual_emenda    7090 non-null   float64
 11  empenhado               7090 non-null   float64
 12  liquidado               7090 non-null   float64
 13  pago                    7090 non-null   float64
dtypes: float64(5), int64(2), object(7)
memory usage: 775.6+ KB

### **Desafio 4: Verificar e tratar valores ausentes**
Verifique se há valores ausentes (nulos) no dataset.

---
## **Etapa 2: Análise Exploratória de Dados**

### **Desafio 5: Agrupar dados por uma coluna específica**

Agrupe os dados pela coluna 'órgão' e calcule a média a partir de outra coluna numérica 'empenhado'. Com este código, você vai responder: "Qual o valor médio empenhado em emendas parlamentares para cada órgão?".

### **Desafio 6: Agrupar dados por duas ou mais colunas**

Desenvolva um código para responder: **Qual o total empenhado por partido em cada órgão?**

### **Desafio 7: Aplicar múltiplas agregações**

Aplique diferentes operações (média, soma e contagem) em colunas numéricas, agrupando por uma coluna categórica. Utilize as colunas que preferir para resolver este desafio.

### **Desafio 8: Criar uma tabela dinâmica (pivot table)**

Crie uma tabela dinâmica (pivot table) usando 'uf_autor' como índice e 'partidos' como colunas, agregando os valores 'empenhados'.

### **Desafio 9: Criar um boxplot**
Crie um boxplot para visualizar a distribuição dos valores na coluna 'empenhado' em cada tipo de autor.

### **Desafio 10: Criar um histograma**
Crie um histograma para visualizar a distribuição de frequências da coluna 'empenhado'.

## **Desafio Extra: Explorar uma base de dados do IBGE**


A plataforma [SIDRA do IBGE](https://sidra.ibge.gov.br/) é uma importante fonte de dados públicos do Brasil e oferece uma ampla diversidade de tabelas que exploram diferentes temáticas. Por exemplo, existem tabelas que fornecem dados sobre a população residente por situação do domicílio e sexo, como também tabelas que apresentam informações sobre a produção agrícola municipal. Para análises econômicas, existem tabelas que registram o PIB dos municípios. No campo da educação, existem tabelas que trazem dados sobre a taxa de escolarização por faixa etária, dentro outros.

**Seu desafio é escolher uma das bases disponíveis na plataforma, baixar e ler neste notebook. Em seguida, faça uma breve análise exploratória de dados (em resumo, visualize e compare uma ou duas colunas)**